version: '3.7'

services:
    php:
        build:
            context: devops/containers/php
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            HOME: /tmp

    nginx:
        image: nginx:1.17-alpine
        volumes:
            - ./devops/containers/nginx/shopware.conf:/etc/nginx/conf.d/default.conf:ro

    mariadb:
        image: mariadb:10.4.18
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_DATABASE: sensormon

    mailhog:
        image: mailhog/mailhog
        environment:
            MH_UI_WEB_PATH: mailhog

    adminer:
        image: adminer:latest

    redis:
        image: redis:6-alpine

volumes:
    mariadb:
    elasticsearch:
